name: conversion_app
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to:


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter_spinkit: ^4.1.2
  http: ^0.12.2
  flutter:
    sdk: flutter




  cupertino_icons: ^0.1.3

dev_dependencies:

  flutter_test:
    sdk: flutter



flutter:


  uses-material-design: true
  assets:
    - images/

  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg


  # https://flutter.dev/assets-and-images/#resolution-aware.



  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
